vidly/vidly/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace vidly.Models
{
    public class Movie
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Required")]
        [MaxLength(50)]
        public string  Name { get; set; }
        [Display(Name = "Release Date")]
        public DateTime ReleaseDate { get; set; }
        [Display (Name = "Date Added")]
        public DateTime DateAdded { get; set; }
        [Display(Name = "In Stock")]
        public int NumberInStock { get; set; }
        public Genre Genre { get; set; }
        [Display(Name = "Genre")]
        public int GenreId { get; set; }
    }
}

vidly/vidly/Controllers/Api/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using AutoMapper;
using vidly.Dtos;
using vidly.Models;

namespace vidly.Controllers.Api
{
   
    public class MovieController : ApiController
    {
        private ApplicationDbContext _context;

        public MovieController()
        {
            _context = new ApplicationDbContext();
        }

        //GET /api/movies
        public IEnumerable<MovieDto> GetMovies()
        {
            return _context.Movies.ToList().Select(Mapper.Map<Movie, MovieDto>);
        }

        //GET /api/movies/1
        /*public MovieDto GetMovie(int id)
        {
            var movie = _context.Movies.SingleOrDefault(c => c.Id == id);
            if (movie == null)
            {
                throw new HttpResponseException(HttpStatusCode.NotFound);
            }

            return Mapper.Map<Movie, MovieDto>(movie);
        }*/
        public IHttpActionResult GetMovie(int id)
        {
            var movie = _context.Movies.SingleOrDefault(c => c.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return Ok(Mapper.Map<Movie, MovieDto>(movie));
        }

        /*//POST /api/movies
        [HttpPost]
        public MovieDto PostMovie(MovieDto movieDto)
        {
            if (!ModelState.IsValid)
            {
                throw new HttpResponseException(HttpStatusCode.BadRequest);
            }

            var movie = Mapper.Map<MovieDto, Movie>(movieDto);
            _context.Movies.Add(movie);
            _context.SaveChanges();
            movieDto.Id = movie.Id;
            return movieDto;
        }*/

        [HttpPost]
        public IHttpActionResult PostMovie(MovieDto movieDto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var movie = Mapper.Map<MovieDto, Movie>(movieDto);
            _context.Movies.Add(movie);
            _context.SaveChanges();
            movieDto.Id = movie.Id;
            return Created(new Uri(Request.RequestUri + "/" + movie.Id), movieDto);
        }



        //PUT /api/movie/1
        [HttpPut]
        public void UpdateMovie(int id, MovieDto movieDto)
        {
            if (!ModelState.IsValid)
            {
                throw new HttpResponseException(HttpStatusCode.BadRequest);
            }

            var movieInDb = _context.Movies.SingleOrDefault(c => c.Id == id);
            if (movieInDb == null)
            {
                throw new HttpResponseException(HttpStatusCode.NotFound);
            }

            Mapper.Map(movieDto, movieInDb);
            /*
                    With Mapper we dont need the following assignments
                    movieInDb.Name = movieDto.Name;
                    movieInDb.BirthDate = movieDto.BirthDate;
                    movieInDb.IsSubscribedToNewsLetter = movieDto.IsSubscribedToNewsLetter;
                    movieInDb.MemberShipTypeId = movieDto.MemberShipTypeId;*/
            _context.SaveChanges();
        }

        //DELETE /api/movies/1
        [HttpDelete]
        public void DeleteMovie(int id)
        {
            var movieInDb = _context.Movies.SingleOrDefault(c => c.Id == id);
            if (movieInDb == null)
            {
                throw new HttpResponseException(HttpStatusCode.NotFound);
            }

            _context.Movies.Remove(movieInDb);
            _context.SaveChanges();
        }
    }
    
}

vidly/vidly/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Data.Entity.Validation;
using vidly.Models;
using vidly.ViewModels;

namespace vidly.Controllers
{
    public class MovieController : Controller
    {
        private ApplicationDbContext _context;

        public MovieController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        // GET: Customer
        public ActionResult Index()
        {
            var customerList = _context.Movies.Include(m => m.Genre).ToList();
            return View(customerList);
        }


        //GET: Customer/Details/1
        public ActionResult Details(int id)
        {
            var movie = _context.Movies.Include(m => m.Genre).SingleOrDefault(m=>m.Id==id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }


        public ActionResult New()
        {
            var genres = _context.Genres.ToList();
            var viewModel = new MovieFormViewModel()
            {
                Movie = new Movie(),
                Genres = genres,
                ViewTitle = "Add New Movie"
            };
            return View("MovieForm", viewModel);
        }

        public ActionResult Edit(int id)
        {
            var movie = _context.Movies.SingleOrDefault(m => m.Id == id);
            var genres = _context.Genres.ToList();
            var viewModel = new MovieFormViewModel()
            {
                Movie = movie,
                Genres = genres,
                ViewTitle = "Edit Movie"
            };
            return View("MovieForm", viewModel);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Movie movie)
        {
            var genres = _context.Genres.ToList();
            if (!ModelState.IsValid)
            {
                var viewModel = new MovieFormViewModel()
                {
                    Genres = genres,
                    Movie = movie
                };
                return View("MovieForm", viewModel);
            }
            if (movie.Id == 0)
            {
                _context.Movies.Add(movie);
            }
            else
            {
                var movieInDb = _context.Movies.Single(c => c.Id == movie.Id); //This will thrown an exception if customer is not found
                //TryUpdateModel(customerInDb); //Don't try to update all properties with this function
                movieInDb.Name = movie.Name;
                movieInDb.ReleaseDate= movie.ReleaseDate;
                movieInDb.GenreId = movie.GenreId;
                movieInDb.DateAdded = movie.DateAdded;
                //We can use Auto Mapper to map, but still consider limited amount of info which user can update

            }

            try
            {
                _context.SaveChanges();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
            
            return RedirectToAction("Index", "Customer");
        }
    }
}

vidly/vidly/Views/Movie/Details.cshtml
@model vidly.Models.Movie
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>
<ul>
    <li>Genre: @Model.Genre.Name</li>
    <li>Date Added: @Model.DateAdded.ToShortDateString()</li>
    <li>Release Date: @Model.ReleaseDate.ToShortDateString()</li>
    <li>Number In Stock : @Model.NumberInStock</li>
</ul>

vidly/vidly/Views/Movie/Index.cshtml
@model IEnumerable<vidly.Models.Movie>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Movies</h2>
<p>
    @Html.ActionLink("New Movie", "New", "Movie", null, new {@class="btn btn-primary"})
</p>
<table id="movies" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th scope="col">Movie</th>
            <th>Genre</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var movie in Model)
            {   <tr>
                    <td>
                        @Html.ActionLink(linkText:@movie.Name, actionName:"Edit", controllerName:"Movie", routeValues: new {id=@movie.Id}, htmlAttributes:null)
                    </td>
                    <td>@movie.Genre.Name</td>
                </tr>
            }
        }
    </tbody>
</table>

vidly/vidly/Views/Movie/MovieForm.cshtml
@model vidly.ViewModels.MovieFormViewModel
@{
    ViewBag.Title = "MovieForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>@Model.ViewTitle</h2>

@using (Html.BeginForm(actionName: "Save", controllerName: "Movie"))
{
    @Html.ValidationSummary(true, "Please fix the following errors")
    <div class="form-group">
        @Html.LabelFor(m => m.Movie.Name)
        @Html.TextBoxFor(m => m.Movie.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Movie.Name, null, htmlAttributes: new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Movie.ReleaseDate)
        @Html.TextBoxFor(m => m.Movie.ReleaseDate, new { @class = "form-control", @type = "date", @ITempDataProvider = "datepicker" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Movie.DateAdded)
        @Html.TextBoxFor(m => m.Movie.DateAdded, new { @class = "form-control", @type = "date", @ITempDataProvider = "datepicker" })

    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Movie.NumberInStock)
        @Html.TextBoxFor(m => m.Movie.NumberInStock, new { @class = "form-control", placeholder = "0" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Movie.GenreId)

        @Html.DropDownListFor(m => m.Movie.GenreId,
            new SelectList(Model.Genres, "Id", "Name"),
            "Select A Genre", new { @class = "form-control" })
        @{
            if (@Model.Movie.GenreId != null)
            {
                <p>@Model.Movie.GenreId</p>
            }
            else
            {
                <p>Null</p>
            }
        }

    </div>

    @Html.HiddenFor(m => m.Movie.Id)
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-primary">Save</button>
}

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
}